version: '2'
services:
  dbrelease:

    image: postgres:11
    user: root
    container_name: postgresrelease
    ports:
     - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      
    restart: always
#    volumes:
#        - ./postgresql:/var/lib/postgresql/data


  odoorelease:

    image: odoo:13
    user: root
    container_name: odoorelease
    depends_on:

      - dbrelease

    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./release/data:/var/lib/odoo
      - ./release/addons:/mnt/extra-addons
      - ./release/etc/odoo.conf:/etc/odoo.conf
    restart: always   
