version: '2'
services:
  db:
    image: postgres:11
    container_name: postgresprod
    user: root
    ports:
     - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      
    restart: always  
#    volumes:
#        - ./postgresql:/var/lib/postgresql/data

  odoo13:
    image: odoo:13
    container_name: odooprod
    user: root
    depends_on:
      - db
    ports:
      - "10013:8069"
      - "20013:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc/odoo.conf:/etc/odoo.conf
    restart: always
