{
    "name": "Base report xlsx",
    "summary": "Base module to create xlsx report",
    "author": "EthiopiaTaxi",
    "website": "https://www.ethiopiataxi.com",
    "category": "Reporting",
    "version": "14.0.1.0.4",
    "development_status": "Production/Stable",
    "license": "AGPL-3",
    "external_dependencies": {"python": ["xlsxwriter", "xlrd"]},
    "depends": ["base", "web"],
    "data": ["views/webclient_templates.xml"],
    "demo": ["demo/report.xml"],
    "installable": True,
}
